name: Node.js CI

on:
  push:
    branches: [ "lesson/response-validation" ]
  pull_request:
    branches: [ "lesson/response-validation" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Run tests with Jest HTML Reporter
      run: npm test -- --reporters=jest-html-reporters

       - name: send telegram message on push
      uses: appleboy/telegram-action@master
      with:
        to: -4240419843
        token: "7263522865:AAF0LYny08mdKvFaX8qCItnI34nRBtaWfQs"
        photo: 
        message: |
          ${{ github.actor }} created commit new view:
          Commit message: ${{ github.event.commits[0].message }}

          Repository: ${{ github.repository }}

          See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}